language: php

php:
  - 5.3
  - 5.4

env:
  - PARALLEL=false
  - PARALLEL=true

script:
  - if [[ "$PARALLEL" == "false" ]]; then php tests/AllTests.php; fi
  - if [[ "$PARALLEL" == "true" ]]; then php tests/AllTestsParallel.php; fi